
spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    password: password
    user: admin
  datasource:
    url:
    driver-class-name: org.postgresql.Driver
    password:
    username:
